### PR TITLE
Fixed missing leasing price in woocommerce shortcode [products]

### PR DESCRIPTION
**Pull request by nalezny**

### CODE REVIEW

**Comment by kavhad** [comment]
Previously the action hook for woocommerce_before_shop_loop -> **save_product_prices** was used to fetch and store monthly cost data for all products for one page, but with your above mentioned change you disregard this logic and simply fetch data for each product when it's going to be displayed. This might slow certain pages down, for instance a page that shows lets say 300 products need to do 300 sequential api calls.

I'm not sure this change is such a good idea and does it actually solve the bug our client is experiencing?
 I.e could we reproduce the bug?

**Comment by kavhad** [comment]
Managed to reproduce the bug now, but the fix as it's now is not a good general solution as it can cause problems with load times.

**Comment by nalezny** [comment]
Thank you for pointing me in the right direction. I found a suitable hook "woocommerce_shortcode_before_products_loop" for our needs. Also recreated WP_Query with params from this hook to enable pagination, category selection, posts per page, tags, and selecting individual products by their IDs to reduce server requests.

**Comment by kavhad** [comment]
> Thank you for pointing me in the right direction. I found a suitable hook "woocommerce_shortcode_before_products_loop" for our needs. Also recreated WP_Query with params from this hook to enable pagination, category selection, posts per page, tags, and selecting individual products by their IDs to reduce server requests.

Great, but you forgot to revert the **display_leasing_price_per_product** method and so it still called individual API methods. I will make final correction and make a new pull request of it.

**Pull request closed without merging**
